// Uses only one synthetic code and disposable tasks, never participant labs.
const {chromium}=require('playwright');
const {execFileSync}=require('node:child_process');
const {randomInt,createHash}=require('node:crypto');
const assert=require('node:assert/strict');
const alphabet='ABCDEF012345678',code=Array.from({length:10},()=>alphabet[randomInt(alphabet.length)]).join('');
const id=createHash('sha256').update(code).digest('hex'),S=x=>({S:x}),table='yolomancer-dispenser';
function aws(args,profile='default'){const raw=execFileSync('aws',['--profile',profile,'--region','eu-west-1',...args,'--output','json'],{encoding:'utf8'});return raw.trim()?JSON.parse(raw):null;}
const get=pk=>aws(['dynamodb','get-item','--table-name',table,'--key',JSON.stringify({pk:S(pk)}),'--consistent-read'])?.Item;
const taskStatus=task=>aws(['ecs','describe-tasks','--cluster','yolomancer-lab','--tasks',task],'prosus-user-000').tasks[0]?.lastStatus;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
let browser,created=false;const tasks=new Set();
(async()=>{try{
 const epoch=Math.floor(Date.now()/1000);
 aws(['dynamodb','put-item','--table-name',table,'--condition-expression','attribute_not_exists(pk)','--item',JSON.stringify({pk:S('code#'+id),lab_test:{BOOL:true},expires_at:{N:String(epoch+72*3600)},ttl:{N:String(epoch+72*3600)},account_user:S('prosus-user-100'),credentials:S(JSON.stringify({aws_access_key_id:'AKIA'+'A'.repeat(16),aws_secret_access_key:'x'.repeat(40),aws_region:'eu-west-1'}))})]);created=true;
 const ip=execFileSync('dig',['+short','lab.yolomancer.com','A','@1.1.1.1'],{encoding:'utf8'}).trim().split('\n').find(x=>/^\d+\.\d+\.\d+\.\d+$/.test(x));
 browser=await chromium.launch({args:ip?[`--host-resolver-rules=MAP lab.yolomancer.com ${ip}`]:[]});
 const page=await browser.newPage();await page.goto('https://lab.yolomancer.com/terminal.html');
 await page.waitForFunction(()=>typeof initConnection==='function',null,{timeout:90000});
 const post=(path,body)=>page.evaluate(async({path,body})=>{const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return r.status;},{path,body});
 assert.equal(await post('/api/delete',{confirm:true,generation:'wrong'}),403);
 assert.equal(await post('/api/reinstall',{confirm:true,generation:'wrong'}),403);
 console.log('PASS unauthenticated actions rejected');
 await page.locator('#code').fill(code);await page.locator('#onboard button').click();
 await page.locator('#delete-lab').waitFor({state:'visible',timeout:90000});
 let item=get('lab#'+id),record=JSON.parse(item.data.S),first=record.generation;
 const oldBootstrap={id,token:record.bootstrapToken};
 assert.equal(record.expires-record.created,48*3600);tasks.add(item.task_arn.S);
 console.log('PASS newly provisioned lab has a 48-hour deadline');
 await page.locator('#lab-progress').waitFor({state:'visible'});
 assert((await page.locator('#progress-message').textContent()).length>0);
 assert.match(await page.locator('#progress-step').textContent(),/STEP \d OF 8/);
 assert.equal(await page.locator('#delete-lab').isDisabled(),true);
 assert.equal(await page.locator('#reinstall-lab').isDisabled(),true);
 await page.waitForFunction(()=>document.querySelector('#status').textContent==='CONNECTED',null,{timeout:1200000});
 for(const action of ['delete','reinstall']){
   await page.locator('#'+action+'-lab').click();await page.locator('#lab-action-dialog').waitFor({state:'visible'});
   assert((await page.locator('#action-warning').textContent()).includes('permanently lost'));
   if(action==='reinstall')await page.screenshot({path:'/tmp/yolomancer-reinstall-modal.png'});
   await page.locator('#cancel-action').click();assert.equal(get('lab#'+id).operation,undefined);
 }
 console.log('PASS both warning overlays cancel without modifying the lab');
 assert.equal(await post('/api/delete',{generation:first,confirm:false}),403);
 assert.equal(await post('/api/delete',{generation:'stale',confirm:true}),403);
 assert.equal(get('lab#'+id).operation,undefined);
 console.log('PASS missing confirmation and stale generation rejected');
 await page.locator('#reinstall-lab').click();await page.locator('#confirm-action').click();
 await page.waitForFunction(first=>typeof state!=='undefined'&&state?.generation&&state.generation!==first,first,{timeout:180000});
 item=get('lab#'+id);record=JSON.parse(item.data.S);tasks.add(item.task_arn.S);
 assert.equal(record.reinstalledFrom,first);assert.equal(record.expires-record.created,48*3600);
 assert.equal(aws(['ecs','describe-tasks','--cluster','yolomancer-lab','--tasks',[...tasks][0]],'prosus-user-000').tasks[0].desiredStatus,'STOPPED');
 assert.equal(await post('/api/reinstall',{generation:first,confirm:true}),200);
 assert.equal(JSON.parse(get('lab#'+id).data.S).generation,record.generation);
 assert.equal(await post('/api/delete',{generation:first,confirm:true}),403);
 assert.equal(get('lab#'+id).operation,undefined);
 console.log('PASS reinstall stops old task, reuses code, and retries do not replace the new task');
 for(const endpoint of ['/bootstrap','/progress','/ready'])assert.equal(await post(endpoint,{...oldBootstrap,stage:'failed',fingerprint:Array(16).fill('aa').join(':')}),403);
 assert.equal(get('lab#'+id).progress_stage?.S==='failed',false);
 console.log('PASS superseded task cannot bootstrap or mutate progress/readiness');
 await page.waitForFunction(()=>state?.progress?.step>=3,null,{timeout:180000});
 assert.equal(await page.locator('#lab-action-dialog').evaluate(el=>el.open),false);
 await page.screenshot({path:'/tmp/yolomancer-provision-progress.png'});
 console.log('PASS reinstall continues into provisioning with real bootstrap progress');
 await page.waitForFunction(()=>document.querySelector('#status').textContent==='CONNECTED',null,{timeout:1200000});
 assert.equal(await page.locator('#lab-progress').evaluate(el=>el.hidden),true);
 console.log('PASS replacement finishes source build and connects automatically');
 const savedKey=await page.evaluate(()=>identity.privateKey);
 await page.locator('#delete-lab').click();await page.locator('#confirm-action').click();
 await page.waitForFunction(()=>document.querySelector('#delete-lab').hidden&&document.querySelector('#status').textContent.startsWith('Lab deleted.'),null,{timeout:90000});
 for(let i=0;i<60&&taskStatus(item.task_arn.S)!=='STOPPED';i++)await wait(2000);
 assert.equal(taskStatus(item.task_arn.S),'STOPPED');assert.equal(get('lab#'+id).operation.S,'delete');
 assert.equal(await page.evaluate(async()=>(await identityStore()).privateKey),savedKey);
 console.log('PASS Delete Lab stops the task and retains browser identity');
 const invalidProof=await page.evaluate(async code=>({...await provisionRequest(code),signature:''}),code);
 assert.equal(await post('/api/provision',invalidProof),403);
 assert.equal(get('lab#'+id).operation.S,'delete');
 await page.locator('#code').fill(code);await page.locator('#onboard button').click();
 await page.locator('#delete-lab').waitFor({state:'visible',timeout:90000});
 assert.equal(await page.evaluate(()=>identity.privateKey),savedKey);
 tasks.add(get('lab#'+id).task_arn.S);
 console.log('PASS signed public-key proof provisions another lab with the same SSH identity');
}finally{
 if(browser)await browser.close();
 if(created){const item=get('lab#'+id);if(item?.task_arn?.S)tasks.add(item.task_arn.S);
   for(const task of tasks)if(taskStatus(task)!=='STOPPED')aws(['ecs','stop-task','--cluster','yolomancer-lab','--task',task,'--reason','Synthetic lab action test cleanup'],'prosus-user-000');
   for(const prefix of ['lab#','ssh#'])aws(['dynamodb','delete-item','--table-name',table,'--key',JSON.stringify({pk:S(prefix+id)})]);
   aws(['dynamodb','delete-item','--table-name',table,'--key',JSON.stringify({pk:S('code#'+id)}),'--condition-expression','lab_test = :yes','--expression-attribute-values',JSON.stringify({':yes':{BOOL:true}})]);
   console.log('Removed only synthetic records and tasks; participant labs unchanged.');
 }
}})().catch(e=>{console.error(e.message);process.exitCode=1;});
